name: test
on: 
   push:
   pull_request:
     branches:
            - main
jobs:
    first-job:
       runs-on: ubuntu-latest
       outputs:
         output1: ${{ steps.bus.outputs.data}}
       steps:
          - name: checkout
            uses: actions/checkout@v3
            with:
               fetch-depth: 2

               

          - name: last modified file
            id: new
            run: |
               pwd
               ls -lrt
               git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.sha }} >> diff.txt
              #  git diff --name-only --no-commit-id \
              #  ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} 
                

          - name: chekout common repo 
            run: git clone "https://github.com/amansunny08/march12-common.git"  my-tools
            # uses: actions/checkout@v3
            # with:
            #    repository: amansunny08/https://github.com/amansunny08/march12-common.git
            #    path: my-tools     

          - name: list files
            run: |
               cd my-tools
               ls -lrt    

          - name: run python script
            id: bus
            run: |
              
              abc=my-tools/$(python test.py)
              echo "data=$abc" >> "$GITHUB_OUTPUT" 

          - name: output result
            run: |
              echo "${{ steps.bus.outputs.data}}"       


    second-job:
        needs: first-job
        strategy:
         max-parallel: 1
         matrix: 
            version: ${{ fromJSON(needs.first-job.outputs.output1) }}
        runs-on: ubuntu-latest
        steps:  
           - name: checkout
             uses: actions/checkout@v3

           - name: display output
             run: cat ${{ matrix.version }} 
           
