name: test
on: 
   push:
   pull_request:
     branches:
            - main
jobs:
    first-job:
       runs-on: ubuntu-latest
       outputs:
         output1: ${{ steps.bus.outputs.data}}
       steps:
          - name: checkout
            uses: actions/checkout@v3
            with:
               fetch-depth: 2

          - name: last modified file
            id: new
            run: |
               git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.sha }} >> diff.txt
              #  git diff --name-only --no-commit-id \
              #  ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}  

          - name: run python script
            id: bus
            run: |
              abc=$(python test.py)
              echo "data=$abc" >> "$GITHUB_OUTPUT" 

          - name: output result
            run: |
              echo "${{ steps.bus.outputs.data}}"       


    second-job:
        needs: first-job
        strategy:
         matrix: 
            version: ${{ fromJSON(needs.first-job.outputs.output1) }}
        runs-on: ubuntu-latest
        steps:  
           - name: display output
             run: cat ${{ matrix.version }} 
           
